export const NFTData = [
	{
		avatar: "/assets/av1.png",
		handle: "@knight",
		stars: "231",
		currentBid: "0.54",
		endingIn: "12h 55m 2s",
		nft: "/assets/purple-monkey.png",
	},
	{
		avatar: "/assets/av2.png",
		handle: "@king",
		stars: "399",
		currentBid: "2.7",
		endingIn: "7h 55m 16s",
		nft: "/assets/cool-monkey.png",
	},
	{
		avatar: "/assets/av3.png",
		handle: "@grim",
		stars: "199",
		currentBid: "0.87",
		endingIn: "1h 5m 18s",
		nft: "/assets/cyclops-monkey.png",
	},
	{
		avatar: "/assets/av1.png",
		handle: "@knight",
		stars: "677",
		currentBid: "1.4",
		endingIn: "19h 1m 55s",
		nft: "/assets/glasses-monkey.png",
	},
	{
		avatar: "/assets/av3.png",
		handle: "@grim",
		stars: "654",
		currentBid: "3.8",
		endingIn: "2h 5m 59s",
		nft: "/assets/brain-monkey.png",
	},
	{
		avatar: "/assets/av2.png",
		handle: "@king",
		stars: "99",
		currentBid: "2.7",
		endingIn: "1h 12m 43s",
		nft: "/assets/angry-monkey.png",
	},
]
